---
title: 'Lab 06: Joining Tables'
author: "Reilly Orman"
date: "3/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r Exercise 1.0}
songs <- read_csv("https://raw.githubusercontent.com/bwiernik/progdata-class/master/data/singer/songs.csv")
locations <- read_csv("https://raw.githubusercontent.com/bwiernik/progdata-class/master/data/singer/loc.csv")

(time <- as_tibble(songs) |> 
    rename(song = title))

(album <- as_tibble(locations) |> 
    select(title, everything()) |> 
    rename(album = release,
           song  = title))
```

```{r 1.1}
time |> 
  inner_join(album, by = c("artist_name", "song"))
```

```{r 1.2}
time |> 
  left_join(album, by = c("artist_name", "song"))
```

```{r 1.3}
time |> 
  anti_join(album, by = "song")
```

```{r 1.4}
time |> 
  anti_join(album, by = "artist_name")
```

```{r 1.5}
time |> 
  full_join(album, by = c("artist_name", "song"))
```

```{r Exercise 2.0}
fell <- read_csv("https://raw.githubusercontent.com/jennybc/lotr-tidy/master/data/The_Fellowship_Of_The_Ring.csv")
ttow <- read_csv("https://raw.githubusercontent.com/jennybc/lotr-tidy/master/data/The_Two_Towers.csv")
retk <- read_csv("https://raw.githubusercontent.com/jennybc/lotr-tidy/master/data/The_Return_Of_The_King.csv")
```

```{r 2.1}
FjIntermediate <- full_join(fell, ttow, by = c("Film", "Race", "Female", "Male"))

FjFinal <- full_join(FjIntermediate, retk, by = c("Film", "Race", "Female", "Male"))
FjFinal
```

```{r 2.2}
fell |> 
  anti_join(ttow, by ="Race") |> 
  anti_join(retk, by = "Race")
```

```{r 3.0}
(y <-  tibble(x1 = LETTERS[1:3], x2 = 1:3))

(z <- tibble(x1 = c("B", "C", "D"), x2 = 2:4))
```

```{r 3.1}
intersect(y, z)
```

```{r 3.2}
union(
  mutate(y, day = "Day 1"),
  mutate(z, day = "Day 2")
)
```

```{r 3.3}
setdiff(y, z)
```

