---
title: 'Lab 3: Exploring gapminder with ggplot2 and dplyr'
author: "Reilly Orman"
date: "2/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gapminder)
```

```{r 1.1}
filter(gapminder, country %in% c("France", "Zambia", "Australia") & year <= 1979, year >=1970) 
```


```{r 1.2}
gapminder |>
  filter(country %in% c("France", "Zambia", "Australia") & year <= 1979, year >=1970) |>
  select(country, gdpPercap)
```

```{r 1.3}
new_gap <- gapminder |>
  arrange(year) |> 
  group_by(country) |> 
  mutate(lifeExp_change = lifeExp - lag(lifeExp)) |> 
  filter(lifeExp_change < 0)

new_gap
```

```{r 1.4}
gapminder |>
  group_by(country) |> 
  filter(gdpPercap == max(gdpPercap))
```

```{r 1.5}
canada <- gapminder |> 
  filter(country == "Canada")

ggplot(canada) +
  aes(x = lifeExp, y = gdpPercap) + 
  geom_point(color = "blue") +
  scale_x_continuous("Life expectancy") +
  scale_y_continuous(
   name = "GDP per capita", 
   trans = "log10",
   labels = scales::dollar_format()
  ) +
  labs(title = "Canada's Life Expectancy vs. GDP per Capita")
```



