---
title: 'Lab 4: Personality and Green Reputation'
author: "Reilly Orman"
date: "2/10/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
library("ggplot2")
library("dplyr")
dictionary <- readr::read_csv(here::here("data", "green_dictionary.csv"), na = c(""))
green_data <- readr::read_csv(here::here("data", "green_data.csv"))
```



```{r 1.0}
unique(dictionary)

sort(unique(green_data$green1))
```


```{r recode}
dict <- dictionary |> 
  filter(Keying < 0) |> 
  pull(Item) 

new_green_data <- green_data |> 
  mutate(
    across(
      -id, 
      \(x) recode(x, "1" = 5, "2" = 4, "3" = 3, "4" = 2, "5" = 1, "99" = NA_real_)
      ))
```

```{r total scores}

new_green_data <- new_green_data |>
  mutate(
    green_total = mean(c_across(green1:green5), na.rm = TRUE),
    comp_total = mean(c_across(comp1:comp10), na.rm = TRUE),
    intel_total = mean(c_across(intel1:intel10), na.rm = TRUE),
    open_total = mean(c_across(open1:open10), na.rm = TRUE),
    .before = everything()
    ) |> 
  head()

```

```{r rescale}
dat_green_data <- new_green_data |> 
  mutate(
    across(
      green_total:open_total,
      \(x) 100 * (x-1) / (5-1),
      .names = "{.col}_pomp"
    )
  )
```

```{r}
ggplot(dat_green_data) +
  aes(x = green_total_pomp) +
  geom_histogram()
```

